// Assembles the deliverables from web/ + the wasm-pack output:
//
//   dist/index.html    — full standalone document (open directly or serve)
//   dist/artifact.html — Artifact flavor: no document wrapper, no theme
//                        toggle (the host controls the theme)
//   dist/site/         — GitHub Pages build: adds the DuckDB-WASM "Sonar"
//                        console (worker + 36MB wasm need a real HTTP origin)
//
//   node tools/build.mjs

import { execFileSync } from 'node:child_process';
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const read = (...p) => readFileSync(join(root, ...p), 'utf8');

const css = read('web', 'style.css');
const body = read('web', 'body.html');
const app = read('web', 'app.js');
const wasmB64 = readFileSync(join(root, 'wasm', 'pkg', 'orca_ocean_bg.wasm'))
  .toString('base64');

// wasm-bindgen glue, inlined: drop the ts pragma and the export statement so
// it can live inside one <script type="module"> with the app code.
const glue = read('wasm', 'pkg', 'orca_ocean.js')
  .replace(/^\/\* @ts-self-types=.*\*\/\n/, '')
  .replace(/^export \{ initSync, __wbg_init as default \};\s*$/m, '');

const script = [
  '// --- wasm-bindgen glue (generated by wasm-pack, inlined) ---',
  glue.trim(),
  '',
  `const WASM_B64 = ${JSON.stringify(wasmB64)};`,
  '',
  '// --- page runtime ---',
  app.trim(),
].join('\n');

const themeToggle = `<button class="theme-btn" id="theme-btn" type="button" hidden aria-label="Toggle color theme">
        <svg class="icon-moon" width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 12.8A9 9 0 1 1 11.2 3 7 7 0 0 0 21 12.8z"/></svg>
        <svg class="icon-sun" width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M4.9 4.9l1.4 1.4m11.4 11.4 1.4 1.4M2 12h2m16 0h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/></svg>
      </button>`;

const fontsHref =
  'https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,500..800&family=IBM+Plex+Sans:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500&display=swap';

const favicon =
  'data:image/svg+xml,' +
  encodeURIComponent(
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="7" fill="#071019"/><g fill="#5ce4d0"><circle cx="7" cy="16" r="2.6"/><circle cx="16" cy="16" r="2.6"/><circle cx="25" cy="16" r="2.6"/><circle cx="11.5" cy="9" r="1.8" opacity="0.6"/><circle cx="20.5" cy="23" r="1.8" opacity="0.6"/></g></svg>`,
  );

const description =
  'Portfolio of a site reliability engineer for AI/ML infrastructure — ' +
  'GPU platforms, distributed training, observability. ' +
  'The background is a live Rust → WebAssembly orca simulation.';

// --- Standalone document ---------------------------------------------------

const standalone = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="color-scheme" content="dark light">
  <title>Depth Log · SRE for AI/ML Infrastructure</title>
  <meta name="description" content="${description}">
  <meta property="og:type" content="website">
  <meta property="og:title" content="Depth Log">
  <meta property="og:description" content="${description}">
  <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#071019">
  <meta name="theme-color" media="(prefers-color-scheme: light)" content="#eef4f6">
  <link rel="icon" href="${favicon}">
  <script>
    // Pre-paint theme stamp: avoids a wrong-theme flash for saved choices.
    try {
      var t = localStorage.getItem('theme');
      if (t === 'light' || t === 'dark') document.documentElement.dataset.theme = t;
    } catch (e) {}
  </script>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="stylesheet" href="${fontsHref}" media="print" onload="this.media='all'">
  <noscript><link rel="stylesheet" href="${fontsHref}"></noscript>
  <style>
${css}
  </style>
</head>
<body>
${body.replace('<!--THEME_TOGGLE-->', themeToggle)}
<script type="module">
${script}
</script>
</body>
</html>
`;

// --- Artifact flavor -------------------------------------------------------
// No doctype/html/head/body wrapper (the artifact host provides it) and no
// theme toggle (the host stamps data-theme on the root itself).

const artifact = `<title>Depth Log</title>
<link rel="stylesheet" href="${fontsHref}">
<style>
${css}
</style>
${body.replace('<!--THEME_TOGGLE-->', '')}
<script type="module">
${script}
</script>
`;

mkdirSync(join(root, 'dist'), { recursive: true });
writeFileSync(join(root, 'dist', 'index.html'), standalone);
writeFileSync(join(root, 'dist', 'artifact.html'), artifact);

// --- GitHub Pages build with the DuckDB console ----------------------------

const consoleHtml = read('web', 'console.html');
const site = standalone
  .replace('<!--CONSOLE-->', consoleHtml)
  .replace(
    '</body>',
    '<script type="module" src="./assets/console.js"></script>\n</body>',
  );

const assetsDir = join(root, 'dist', 'site', 'assets');
mkdirSync(assetsDir, { recursive: true });
writeFileSync(join(root, 'dist', 'site', 'index.html'), site);
// The duckdb-wasm ESM entry bare-imports apache-arrow, so the console module
// must be bundled; the worker and wasm binary are self-contained copies.
execFileSync(join(root, 'node_modules', '.bin', 'esbuild'), [
  join(root, 'web', 'console.js'),
  '--bundle', '--format=esm', '--minify',
  `--outfile=${join(assetsDir, 'console.js')}`,
], { stdio: 'inherit' });
const duckdbDist = join(root, 'node_modules', '@duckdb', 'duckdb-wasm', 'dist');
for (const f of ['duckdb-browser-eh.worker.js', 'duckdb-eh.wasm']) {
  copyFileSync(join(duckdbDist, f), join(assetsDir, f));
}

const kb = (s) => `${(Buffer.byteLength(s) / 1024).toFixed(1)} KB`;
console.log(`dist/index.html    ${kb(standalone)}`);
console.log(`dist/artifact.html ${kb(artifact)}`);
console.log(`dist/site/         index ${kb(site)} + duckdb assets`);
