// Seed data for the in-browser DuckDB — the same content the static page
// ships, so the first render and the database always agree.

export const CV = {
  experience: [
    {
      depth_m: 0,
      role: 'Site Reliability Engineer III',
      org: 'F5',
      org_url: null,
      link_url: null,
      link_label: null,
      start_label: 'Apr 2024', dt_start: '2024-04',
      end_label: null, dt_end: null,
      bullets: [
        'Shipped an AppStack feature that installs NVIDIA drivers and CUDA for modern GPUs across managed Kubernetes clusters.',
        'Enabled deployment on KVM-class environments with L4 GPU passthrough via AppStack VMs.',
        'Took over a stalled Loki logging-platform migration and led it to completion — on-premise to EKS with an S3 backend, eliminating hardware-capacity toil and enabling on-demand scale-out.',
        'Retired the in-house templating system behind the Loki deployment in favor of the official Helm chart, aligning operations with community standards.',
      ],
    },
    {
      depth_m: 150,
      role: 'MLOps Engineer',
      org: 'Cluster (freelance)',
      org_url: 'https://cluster.mu/en',
      link_url: null,
      link_label: null,
      start_label: '2024', dt_start: '2024',
      end_label: '2024', dt_end: '2024',
      bullets: [
        'Tuned training-data load performance on an HPC system for ML using striping — accelerating training by ~30%.',
        'Built a distributed training pipeline with Ray and Weights & Biases on AWS.',
        'Drove an LLM chatbot project — evaluating models, methods, and vector DBs — then handed the system to SWEs.',
      ],
    },
    {
      depth_m: 300,
      role: 'DevOps Engineer',
      org: 'Binance',
      org_url: null,
      link_url: null,
      link_label: null,
      start_label: 'Aug 2022', dt_start: '2022-08',
      end_label: 'Apr 2024', dt_end: '2024-04',
      bullets: [
        'Led development of a GitOps CI/CD pipeline for Terraform from scratch, integrating Atlantis and Policy-as-Code with OPA.',
        'Directed a VPN migration across multiple AWS accounts using Transit Gateway, VPC endpoints, and Client VPN.',
        'Revived legacy petabyte-scale Hive data pipelines — automated, visualized, and documented them with backfill and retry in a semi-idempotent design.',
      ],
    },
    {
      depth_m: 450,
      role: 'Co-Founder / Tech Lead',
      org: 'MaskTap',
      org_url: null,
      link_url: 'https://www.youtube.com/watch?v=vvvIVb-TGU8',
      link_label: 'demo video ↗',
      start_label: 'Jul 2021', dt_start: '2021-07',
      end_label: 'Jul 2022', dt_end: '2022-07',
      bullets: [
        'Designed and built an auto-anonymization product from scratch around an extensible API.',
        'Developed a framework that automatically masks PII in compliance with GDPR and APPI — original enough to be considered for a patent application.',
      ],
    },
    {
      depth_m: 600,
      role: 'Machine Learning Engineer',
      org: 'Research Center for Advanced Science and Technology, The University of Tokyo (freelance)',
      org_url: null,
      link_url: 'https://arxiv.org/abs/2106.15361',
      link_label: 'arXiv paper ↗',
      start_label: 'Nov 2020', dt_start: '2020-11',
      end_label: 'Jul 2021', dt_end: '2021-07',
      bullets: [
        'Created a computer-vision segmentation model end to end, starting from planning what data to collect and how much.',
        'Diagnosed an unbalanced, undersized dataset in the first PoC and delivered a model that generalizes — the project resulted in an arXiv publication (arxiv.org/abs/2106.15361).',
      ],
    },
    {
      depth_m: 750,
      role: 'Site Reliability Engineer',
      org: 'SoftBank',
      org_url: null,
      link_url: null,
      link_label: null,
      start_label: 'Apr 2020', dt_start: '2020-04',
      end_label: 'Aug 2022', dt_end: '2022-08',
      bullets: [
        'Built and operated a production Kubernetes ML-inference platform, with scheduled autoscaling that absorbed traffic surges during large events.',
        'Designed end-user APIs on the AI platform using Kubernetes CRDs while preserving compatibility for existing users.',
        'Shipped a serverless Vue web app designed for easy maintenance and scale.',
      ],
    },
    {
      depth_m: 900,
      role: 'ML Engineer / Tech Lead',
      org: 'BEENOS (part-time → freelance)',
      org_url: null,
      link_url: null,
      link_label: null,
      start_label: 'Jul 2017', dt_start: '2017-07',
      end_label: '2022', dt_end: '2022',
      bullets: [
        'Led a team of five as tech lead: Python, Node, AWS, Terraform, GitHub Actions, Kubernetes.',
        'Built an ML system for importance discrimination end to end — data collection through deployment.',
        'Replaced a legacy monolith crawler with a Pub/Sub architecture for reliability.',
      ],
    },
  ],

  skills: [
    ['SRE', ['Kubernetes', 'CI/CD', 'AWS', 'Google Cloud', 'Terraform', 'Linux', 'Networking']],
    ['Backend', ['Python', 'Go', 'Rust', 'Java', 'FastAPI', 'Django', 'Laravel']],
    ['Machine learning', ['PyTorch', 'Deep learning', 'NLP', 'MLOps', 'Prompt engineering']],
    ['Observability', ['Loki', 'Prometheus', 'Grafana', 'Vector', 'Fluent Bit', 'Elasticsearch']],
    ['Data', ['Hive', 'Spark', 'Kafka', 'ClickHouse', 'BigQuery', 'Dagster']],
  ],

  signals: [
    ['Open source', 'Contributor to Ray, DeepEval, the Loki Helm chart (Grafana community), and official AWS repositories', 'upstream fixes and features grown out of production SRE and MLOps work', null],
    ['Awards', 'Top 3 — PWS Cup 2021, privacy-protection technology competition', 'Computer Security Symposium · 2021', 'https://www.iwsec.org/pws/2021/cup21_e.html'],
    ['Certifications', 'CKA — Certified Kubernetes Administrator', 'The Linux Foundation · 2024', null],
    ['Certifications', 'Kaggle Competitions Expert', 'Kaggle · 2024', null],
    ['Certifications', 'AWS Certified SysOps Administrator — Associate', 'AWS · 2021', null],
    ['Certifications', 'On-The-Ground Special Radio Operator', 'The Government of Japan · 2018', null],
    ['Certifications', 'JSBA Badge Test Level 1', 'Japan Snowboarding Association · 2026', null],
  ],
};
